---
title: "Ideal Combos"
output: html_document
---
#Packages
```{r}
library(readr)
library(dplyr)
library(tidyverse)
library(janitor)
library(purrr)
library(ggplot2)
library(scales)
library(reactable)
library(tidyr)
library(reactable)
library(shiny)
library(crosstalk)
library(shinythemes)
library(bslib)
library(rsconnect)
```

#Data
```{r}
Comp_Percentage_Data <- read_rds("Completion_Percentage_Data.rds") %>%
  rename("CP_Estimate" = "prob") %>%
  dplyr::select(
    -occurances,
    -std.error,
    -lci,
    -uci,
    -estimate,
    -Prob_Greater_Than_Average
  )

EPA_Data             <- read_rds("EPA_Data.rds") %>%
  rename("EPA_Estimate" = "value") %>%
  dplyr::select(
    -occurances,
    -se
  )
  
```

#Merge data
```{r}
Data <- EPA_Data %>%
  left_join(Comp_Percentage_Data, by = c("CoverageScheme", "combo"))

rm(Comp_Percentage_Data)
rm(EPA_Data)
```

#Plot combos estimated CP & EPA
```{r}
Data %>%
  ggplot(aes(x=CP_Estimate, y = EPA_Estimate))+
  geom_point(shape = 21, colour = "black", fill = "#013369", size = 3, stroke = 1)+
  ylab("EPA Estimate") +
  xlab("Completion Percentage Estimate")+
  theme_bw() +
  theme_light()+
  theme(plot.title = element_text(color="black", size=8, face="bold"))+
  theme(plot.title = element_text(size = 10, face = "bold"),
  plot.subtitle = element_text(size = 8))+
  theme(plot.background = element_rect(fill = "gray97"))+
  theme(panel.background = element_rect(fill = "gray97"))+
  labs(title = "Most Plays With a High EPA Also Have a High Completion Percentage",
       subtitle = "Route Combo EPA & CP For Each Route Combo (minimum 10 attempts)",
       caption = "Plot: Joseph Chernak, Data: SIS") +
  geom_hline(yintercept = 0, linetype = "dashed")+
  geom_vline(xintercept = .50 , linetype = "dashed") +
  scale_x_continuous(labels = scales::percent_format(accuracy = 1L), breaks=seq(0, 1, by = .02))
```

So now we can determine what route combos are best against each coverage by capturing the points in the top right of the graph.

#Data for table
```{r}
Table_Data <- Data %>%
  select(CoverageScheme,
         combo,
         CP_Estimate,
         EPA_Estimate) %>%
  arrange(desc(EPA_Estimate)) %>%
  mutate(`Completion Percentage`  = ifelse(CP_Estimate  > .5, "+", "-"),
         `EPA` = ifelse(EPA_Estimate > 0, "+", "-")) %>%
  rename(`Route Combo` = "combo") %>%
  rename(`Completion Percentage Estimate` = "CP_Estimate") %>%
  rename(`EPA Estimate` = "EPA_Estimate") %>% 
  rename(`Coverage Scheme` = "CoverageScheme") %>%
  select(`Route Combo`,
         `Coverage Scheme`,
         `EPA Estimate`,
         `Completion Percentage Estimate`,
         EPA,
         `Completion Percentage`) %>%
  mutate("Normalized Composite" = round(scale(`Completion Percentage Estimate`) + scale(`EPA Estimate`), digits = 3)) %>%
  group_by(`Coverage Scheme`) %>%
  mutate(Ranking = order(order(`Normalized Composite`, decreasing=TRUE))) %>%
  ungroup() %>%
  dplyr::select(-"Normalized Composite") %>%
  relocate(Ranking)

rm(Data)
```

#color function
```{r}
BuYlRd <- function(x) rgb(colorRamp(c("#7fb7d7", "#ffffbf", "#fc8d59"))(x), maxColorValue = 255)
```

#reactable table in shiny app
```{r}
ui <- fluidPage(theme = bs_theme(version = 4, bootswatch = "minty"),
  reactableOutput("table"),
  navbarPage("SIS Analytics Challenge",
  tabPanel("Table of Estimates"),
  tabPanel("Plot of Estimates")
)
)

server <- function(input, output) {
  output$table <- renderReactable({
    Table_Data %>%
 reactable(
  resizable = TRUE, wrap = TRUE, showSortIcon = FALSE, highlight = TRUE,
    # ALL one page option (no scrolling or page swapping)
    pagination = TRUE,
    # compact for an overall smaller table width wise
    compact = TRUE,
    # borderless - TRUE or FALSE
    borderless = FALSE,
    # fullWidth - either fit to width or not
    fullWidth = FALSE,
  filterable = TRUE,
           columns = list(
    `Route Combo`     = colDef(align = "left", minWidth = 230),
    `Coverage Scheme` = colDef(name = "Coverage", align = "left", minWidth = 150),
    `Completion Percentage Estimate` =   colDef(name = "Completion Percentage", minWidth = 200, align = "center" ,  format = colFormat(percent = T , digits = 1),
          style = function(value) {
          value
          normalized <- (value - min(Table_Data$`Completion Percentage Estimate`)) / (max(Table_Data$`Completion Percentage Estimate`) - min(Table_Data$`Completion Percentage Estimate`))
          color <- BuYlRd(normalized)
          list(background = color)
        }),
    `EPA Estimate` = colDef(name = "EPA" , align = "center",  minWidth = 200, format = colFormat(digits = 4),
    style = function(value) {
          value
          normalized <- (value - min(Table_Data$`EPA Estimate`)) / (max(Table_Data$`EPA Estimate`) - min(Table_Data$`EPA Estimate`))
          color <- BuYlRd(normalized)
          list(background = color)
        },
    class = "border-left"),
    `EPA` = colDef(align = "center",  minWidth = 200, 
                   class = "cell number border-left",
                 cell = function(value) {
                   if (value == "+")
                     tagAppendAttributes(shiny::icon("plus"))
                   else
                     tagAppendAttributes(shiny::icon("minus"))
                   },
                 style = function(value) {
                   if (value == "+") {
                     color <- "green"
                     } else {
                       color <- "red"
                       }
                   list(color = color)
                   }),
    `Completion Percentage` = colDef(align = "center", minWidth = 250,
                 cell = function(value) {
                   if (value == "+")
                     tagAppendAttributes(shiny::icon("plus"))
                   else
                     tagAppendAttributes(shiny::icon("minus"))
                   },
                 style = function(value) {
                   if (value == "+") {
                     color <- "green"
                     } else {
                       color <- "red"
                       }
                   list(color = color)
                   }),
    `Ranking` = colDef(align = "left", minWidth = 50, name = "Rank" )),
  columnGroups = list(
    colGroup(name = "Estimates", columns = c("EPA Estimate", "Completion Percentage Estimate")),
    colGroup(name = "Overall Effectiveness", columns = c("EPA", "Completion Percentage"))
  ))
  })
  }

shinyApp(ui, server)

```
